"""add_user_device_advice_daily_tables

Revision ID: 471ad629ed7a
Revises: 
Create Date: 2025-11-26 23:27:01.914387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471ad629ed7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('request_size', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('food_count', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_logs_user_date', 'api_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_created_at'), 'api_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_device_id'), 'api_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_api_logs_endpoint'), 'api_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_logs_id'), 'api_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_logs_session_id'), 'api_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_api_logs_user_id'), 'api_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('phone_id', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('target_protein', sa.Float(), nullable=True),
    sa.Column('target_carbs', sa.Float(), nullable=True),
    sa.Column('target_fat', sa.Float(), nullable=True),
    sa.Column('dietary_preference', sa.String(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('health_conditions', sa.JSON(), nullable=True),
    sa.Column('total_meals', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_days_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_id'), 'users', ['phone_id'], unique=False)
    op.create_table('daily_nutrition',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('breakfast_count', sa.Integer(), nullable=True),
    sa.Column('lunch_count', sa.Integer(), nullable=True),
    sa.Column('dinner_count', sa.Integer(), nullable=True),
    sa.Column('snack_count', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('calories_pct', sa.Float(), nullable=True),
    sa.Column('protein_pct', sa.Float(), nullable=True),
    sa.Column('carbs_pct', sa.Float(), nullable=True),
    sa.Column('fat_pct', sa.Float(), nullable=True),
    sa.Column('top_foods', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_user_date', 'daily_nutrition', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_date'), 'daily_nutrition', ['date'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_user_id'), 'daily_nutrition', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('paired_device_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('meal_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('auto_capture_interval', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('food_count', sa.Integer(), nullable=True),
    sa.Column('baseline_foods', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_user_time', 'meal_sessions', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_meal_sessions_id'), 'meal_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_meal_sessions_status'), 'meal_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_meal_sessions_user_id'), 'meal_sessions', ['user_id'], unique=False)
    op.create_table('meal_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('snapshot_type', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('delta_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['meal_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_snapshots_captured_at'), 'meal_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_meal_snapshots_id'), 'meal_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_meal_snapshots_session_id'), 'meal_snapshots', ['session_id'], unique=False)
    op.create_table('nutrition_advices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('advice_type', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['meal_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_advices_id'), 'nutrition_advices', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_advices_session_id'), 'nutrition_advices', ['session_id'], unique=False)
    op.create_index(op.f('ix_nutrition_advices_user_id'), 'nutrition_advices', ['user_id'], unique=False)
    op.create_table('snapshot_foods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chinese_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('cooking_method', sa.String(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('calories_kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('nutrition_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['meal_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_foods_id'), 'snapshot_foods', ['id'], unique=False)
    op.create_index(op.f('ix_snapshot_foods_snapshot_id'), 'snapshot_foods', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_foods_snapshot_id'), table_name='snapshot_foods')
    op.drop_index(op.f('ix_snapshot_foods_id'), table_name='snapshot_foods')
    op.drop_table('snapshot_foods')
    op.drop_index(op.f('ix_nutrition_advices_user_id'), table_name='nutrition_advices')
    op.drop_index(op.f('ix_nutrition_advices_session_id'), table_name='nutrition_advices')
    op.drop_index(op.f('ix_nutrition_advices_id'), table_name='nutrition_advices')
    op.drop_table('nutrition_advices')
    op.drop_index(op.f('ix_meal_snapshots_session_id'), table_name='meal_snapshots')
    op.drop_index(op.f('ix_meal_snapshots_id'), table_name='meal_snapshots')
    op.drop_index(op.f('ix_meal_snapshots_captured_at'), table_name='meal_snapshots')
    op.drop_table('meal_snapshots')
    op.drop_index(op.f('ix_meal_sessions_user_id'), table_name='meal_sessions')
    op.drop_index(op.f('ix_meal_sessions_status'), table_name='meal_sessions')
    op.drop_index(op.f('ix_meal_sessions_id'), table_name='meal_sessions')
    op.drop_index('idx_session_user_time', table_name='meal_sessions')
    op.drop_table('meal_sessions')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_daily_nutrition_user_id'), table_name='daily_nutrition')
    op.drop_index(op.f('ix_daily_nutrition_date'), table_name='daily_nutrition')
    op.drop_index('idx_daily_user_date', table_name='daily_nutrition')
    op.drop_table('daily_nutrition')
    op.drop_index(op.f('ix_users_phone_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_api_logs_user_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_session_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_endpoint'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_device_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_created_at'), table_name='api_logs')
    op.drop_index('idx_api_logs_user_date', table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
