"""add_user_profile_fields

Revision ID: 9e69bd808f4d
Revises: 471ad629ed7a
Create Date: 2025-11-27 11:17:20.747896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e69bd808f4d'
down_revision: Union[str, Sequence[str], None] = '471ad629ed7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('health_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('target_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('dietary_preferences', sa.JSON(), nullable=True))
    op.drop_column('users', 'dietary_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dietary_preference', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'dietary_preferences')
    op.drop_column('users', 'target_weight')
    op.drop_column('users', 'health_goal')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'bmi')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
